name = "smart-sync-oauth-relay"
main = "src/index.ts"
compatibility_date = "2024-12-01"
routes = [
  { pattern = "auth-smartsync.takezo.dev", custom_domain = true }
]

[vars]
GOOGLE_CLIENT_ID = "135801498656-lfjor2ml3v26t9l63mkoka0bndgl9eue.apps.googleusercontent.com"
GOOGLE_REDIRECT_URI = "https://auth-smartsync.takezo.dev/callback"
